# Generated by Django 4.0.4 on 2022-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='members',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
