# Generated by Django 4.0.4 on 2022-06-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description_book_special_price_and_more'),
        ('members', '0004_members_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
