# Generated by Django 4.0.4 on 2022-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description_book_special_price_and_more'),
        ('members', '0005_alter_members_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='book',
        ),
        migrations.AddField(
            model_name='members',
            name='book_set',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
